name: persian_threads
description: "A new Flutter project."

# Prevents the package from being accidentally published to pub.dev
# This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# You can override these values in flutter build using --build-name and --build-number.
# Read more about versioning at:
# Android: https://developer.android.com/studio/publish/versioning
# iOS: https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# Windows: major, minor, patch, and build suffix
version: 1.0.0+1

environment:
  sdk: "^3.7.2"

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  flutter_sound: ^9.28.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  video_player: ^2.9.5
  visibility_detector: ^0.4.0+2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package contains a set of recommended lints
  # to encourage good coding practices. The lint set is activated in
  # the analysis_options.yaml file.
  flutter_lints: ^5.0.0

flutter:

  # Include the Material Icons font for Material Icons class.
  uses-material-design: true

  assets:
    - assets/img/image.png
    - assets/img/pfp.png
    - assets/videos/sample.mp4

  # To add custom fonts to your application, add a fonts section here.
  # Each entry should have a "family" key with the font family name,
  # and a "fonts" key with a list giving the asset and other descriptors.
  # Example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # See https://flutter.dev/to/font-from-package for details on package fonts.
